/* eslint-disable @typescript-eslint/no-explicit-any, jsx-a11y/label-has-associated-control, jsx-a11y/no-autofocus */
"use client";

import { useRef, useState } from "react";

type Role = "manager" | "fulfillment" | "admin";
type View = "catalog" | "cart" | "history" | "dashboard" | "orders" | "products" | "categories" | "locations" | "receiving" | "adjustment" | "movements" | "users" | "settings";
type Product = { id:number; name:string; sku:string; category:string; description:string; unit:string; onHand:number; reserved:number; low:number; icon:string; archived?:boolean };
type Order = { id:string; manager:string; location:string; status:string; submitted:string; items:number; note:string };

const productsSeed: Product[] = [
  {id:1,name:"Compostable Bowl Lids",sku:"PKG-1042",category:"Packaging",description:"Clear fitted lids for 32 oz bowls",unit:"Case / 300",onHand:18,reserved:6,low:8,icon:"◯"},
  {id:2,name:"Large Paper Bags",sku:"PKG-2110",category:"Packaging",description:"Reinforced handled takeout bags",unit:"Bundle / 250",onHand:7,reserved:5,low:6,icon:"▱"},
  {id:3,name:"Nitrile Gloves — L",sku:"SUP-3008",category:"Supplies",description:"Powder-free black nitrile gloves",unit:"Case / 10 boxes",onHand:24,reserved:3,low:10,icon:"♢"},
  {id:4,name:"Foil Burrito Sheets",sku:"PKG-1009",category:"Packaging",description:"Pre-cut foodservice foil sheets",unit:"Case / 3,000",onHand:0,reserved:0,low:5,icon:"▤"},
  {id:5,name:"Jalapeño Hot Sauce",sku:"PAN-4012",category:"Pantry",description:"House-label hot sauce bottles",unit:"Case / 24",onHand:31,reserved:8,low:12,icon:"♨"},
  {id:6,name:"Receipt Paper",sku:"SUP-2024",category:"Supplies",description:"Thermal register rolls",unit:"Case / 50",onHand:14,reserved:2,low:6,icon:"▥"},
];
const ordersSeed: Order[] = [
  {id:"WH-1048",manager:"Alex R.",location:"Riverside",status:"Submitted",submitted:"Today, 9:42 AM",items:5,note:"Please include extra labels."},
  {id:"WH-1047",manager:"Morgan L.",location:"Downtown",status:"Picking",submitted:"Today, 8:16 AM",items:8,note:"Deliver after 2 PM."},
  {id:"WH-1046",manager:"Jamie S.",location:"Northside",status:"Out for Delivery",submitted:"Yesterday, 3:35 PM",items:3,note:""},
  {id:"WH-1045",manager:"Alex R.",location:"Riverside",status:"Delivered",submitted:"Aug 8, 11:20 AM",items:6,note:"Left with shift lead."},
];
const statusClass = (s:string) => `status status-${s.toLowerCase().replaceAll(" ","-")}`;

export function WarehouseApp() {
  const [role,setRole] = useState<Role|null>(null);
  const [view,setView] = useState<View>("catalog");
  const [pin,setPin] = useState("");
  const [products,setProducts] = useState(productsSeed);
  const [orders,setOrders] = useState(ordersSeed);
  const [cart,setCart] = useState<Record<number,number>>({});
  const [category,setCategory] = useState("All");
  const [search,setSearch] = useState("");
  const [toast,setToast] = useState("");
  const [location,setLocation] = useState("");
  const [note,setNote] = useState("");
  const [selectedOrder,setSelectedOrder] = useState<Order|null>(null);
  const available=(p:Product)=>p.onHand-p.reserved;
  const cartCount=Object.values(cart).reduce((a,b)=>a+b,0);
  const categories=["All",...Array.from(new Set(products.filter(p=>!p.archived).map(p=>p.category)))];
  const filtered=products.filter(p=>!p.archived&&(category==="All"||p.category===category)&&(p.name.toLowerCase().includes(search.toLowerCase())||p.sku.toLowerCase().includes(search.toLowerCase())));
  const notify=(message:string)=>{setToast(message);setTimeout(()=>setToast(""),2400)};
  function login(){ if(pin.length!==4)return notify("Enter a 4-digit code"); const next:Role=pin.startsWith("9")?"admin":"manager"; setRole(next); setView(next==="manager"?"catalog":"dashboard"); }
  function changeQty(id:number,next:number){const p=products.find(x=>x.id===id)!;setCart(c=>({...c,[id]:Math.max(0,Math.min(next,available(p)))}));}
  function submitOrder(){if(!location)return notify("Choose a destination location");if(!cartCount)return notify("Add at least one product"); const order:Order={id:`WH-${1049+orders.length}`,manager:"Alex R.",location,status:"Submitted",submitted:"Just now",items:Object.keys(cart).filter(k=>cart[+k]>0).length,note};setOrders(o=>[order,...o]);setProducts(ps=>ps.map(p=>({...p,reserved:p.reserved+(cart[p.id]||0)})));setCart({});setNote("");setLocation("");setView("history");notify("Warehouse order submitted");}
  function logout(){setRole(null);setPin("");setView("catalog");}

  if(!role) return <Login pin={pin} setPin={setPin} login={login} toast={toast}/>;
  const managerNav:[View,string][]=[["catalog","Catalog"],["cart",`Cart${cartCount?` (${cartCount})`:""}`],["history","My Orders"]];
  const adminNav:[View,string][]=[["dashboard","Dashboard"],["orders","Order Queue"],["products","Products"],["categories","Categories"],["locations","Locations"],["receiving","Receive"],["adjustment","Adjust"],["movements","Movement Log"],["users","Users & Codes"],["settings","Settings"]];
  const nav=role==="manager"?managerNav:adminNav;
  return <div className="app-shell">
    <header className="topbar"><button className="brand" onClick={()=>setView(role==="manager"?"catalog":"dashboard")}><span className="pepper">H</span><span>HABANEROS<small>WAREHOUSE</small></span></button><div className="account"><span className="account-copy"><b>{role==="manager"?"Alex R.":"Taylor M."}</b><small>{role==="manager"?"Store Manager":"Administrator"}</small></span><button className="icon-button" onClick={logout} aria-label="Sign out">↪</button></div></header>
    <div className="body"><aside><nav>{nav.map(([id,label])=><button key={id} className={view===id?"active":""} onClick={()=>setView(id)}><span>{navIcon(id)}</span>{label}</button>)}</nav><div className="warehouse-state"><span className="pulse"/>Warehouse online</div></aside>
    <main>{role==="manager"?<Manager view={view} setView={setView} products={filtered} allProducts={products} categories={categories} category={category} setCategory={setCategory} search={search} setSearch={setSearch} cart={cart} changeQty={changeQty} cartCount={cartCount} location={location} setLocation={setLocation} note={note} setNote={setNote} submitOrder={submitOrder} orders={orders.filter(o=>o.manager==="Alex R.")} selectedOrder={selectedOrder} setSelectedOrder={setSelectedOrder}/>:<Admin view={view} setView={setView} products={products} setProducts={setProducts} orders={orders} setOrders={setOrders} selectedOrder={selectedOrder} setSelectedOrder={setSelectedOrder} notify={notify}/>}</main></div>
    {toast&&<div className="toast">✓ {toast}</div>}
  </div>;
}

function Login({pin,setPin,login,toast}:{pin:string;setPin:(v:string)=>void;login:()=>void;toast:string}){
 const inputRef = useRef<HTMLInputElement>(null);
 return <main className="login-page"><section className="login-card"><div className="login-brand"><span className="pepper large">H</span><h1>HABANEROS<small>WAREHOUSE ORDERING</small></h1></div><div className="rule"/><h2>Welcome back</h2><p>Enter your 4-digit Clover or warehouse access code.</p><label htmlFor="access-code">Access code</label><div className="pin-entry" onClick={()=>inputRef.current?.focus()}><div className="pin-boxes" aria-hidden="true">{[0,1,2,3].map(i=><span key={i}>{pin[i]?"•":""}</span>)}</div><input id="access-code" ref={inputRef} autoFocus className="pin-input" aria-label="4-digit access code" inputMode="numeric" autoComplete="one-time-code" maxLength={4} value={pin} onChange={e=>setPin(e.target.value.replace(/\D/g,"").slice(0,4))} onKeyDown={e=>e.key==="Enter"&&login()}/></div><button className="primary wide" onClick={login}>Continue</button><p className="help">Use the code assigned by your warehouse administrator.<br/>Codes are verified securely in the database.</p></section>{toast&&<div className="toast error">{toast}</div>}</main>
}

function Manager(p:any){
 if(p.selectedOrder) return <OrderDetail order={p.selectedOrder} back={()=>p.setSelectedOrder(null)} manager/>;
 if(p.view==="catalog")return <><PageHead eyebrow="WAREHOUSE CATALOG" title="What does your store need?" subtitle="Choose products and quantities. Availability updates when orders are submitted."/><div className="toolbar"><div className="search">⌕ <input aria-label="Search products" placeholder="Search products or SKU" value={p.search} onChange={(e:any)=>p.setSearch(e.target.value)}/></div><div className="chips">{p.categories.map((c:string)=><button className={p.category===c?"selected":""} key={c} onClick={()=>p.setCategory(c)}>{c}</button>)}</div></div><div className="product-grid">{p.products.map((x:Product)=><ProductCard key={x.id} p={x} qty={p.cart[x.id]||0} change={p.changeQty}/>)}</div>{p.cartCount>0&&<button className="floating-cart" onClick={()=>p.setView("cart")}><span>View cart</span><b>{p.cartCount} units →</b></button>}</>;
 if(p.view==="cart")return <><PageHead eyebrow="YOUR ORDER" title="Review warehouse order" subtitle="Adjust quantities before choosing a destination."/><div className="split"><section className="panel"><h3>Order items <span className="count">{p.cartCount}</span></h3>{Object.entries(p.cart).filter(([,q])=>(q as number)>0).map(([id,q])=>{const x=p.allProducts.find((z:Product)=>z.id===+id);return <div className="cart-row" key={id}><div className="product-icon small">{x.icon}</div><div className="grow"><b>{x.name}</b><small>{x.sku} · {x.unit}</small></div><Qty value={q as number} max={x.onHand-x.reserved} onChange={(v:number)=>p.changeQty(x.id,v)}/><button className="remove" onClick={()=>p.changeQty(x.id,0)}>Remove</button></div>})}{!p.cartCount&&<Empty text="Your cart is empty." action="Browse catalog" onClick={()=>p.setView("catalog")}/>}</section><SubmitPanel {...p}/></div></>;
 return <><PageHead eyebrow="ORDER HISTORY" title="Your warehouse orders" subtitle="Follow every order from submission through delivery."/><OrderList orders={p.orders} select={p.setSelectedOrder}/></>;
}

function ProductCard({p,qty,change}:{p:Product;qty:number;change:(id:number,q:number)=>void}){const avail=p.onHand-p.reserved;return <article className={`product-card ${avail===0?"out":""}`}><div className="product-image"><span>{p.icon}</span>{avail===0&&<b>OUT OF STOCK</b>}</div><div className="product-info"><div className="meta"><span>{p.category}</span><span>{p.sku}</span></div><h3>{p.name}</h3><p>{p.description}</p><small>{p.unit}</small><div className="availability"><span className={avail<=p.low?"low":""}>{avail===0?"Unavailable":`${avail} available`}</span>{avail>0&&<Qty value={qty} max={avail} onChange={v=>change(p.id,v)}/>}</div></div></article>}
function Qty({value,max,onChange}:{value:number;max:number;onChange:(v:number)=>void}){return <div className="qty"><button aria-label="Decrease quantity" onClick={()=>onChange(value-1)} disabled={value===0}>−</button><span>{value}</span><button aria-label="Increase quantity" onClick={()=>onChange(value+1)} disabled={value>=max}>+</button></div>}
function SubmitPanel(p:any){return <section className="panel submit-panel"><h3>Delivery details</h3><label>Destination location <b>*</b></label><select value={p.location} onChange={(e:any)=>p.setLocation(e.target.value)}><option value="">Select a location</option><option>Riverside</option><option>Downtown</option><option>Northside</option></select><label>Order note <span>Optional</span></label><textarea value={p.note} onChange={(e:any)=>p.setNote(e.target.value)} placeholder="Delivery instructions or details for fulfillment…"/><div className="summary"><span>Total units</span><b>{p.cartCount}</b></div><button className="primary wide" onClick={p.submitOrder}>Submit Warehouse Order</button><small className="center">Submitting reserves available warehouse inventory.</small></section>}

function Admin(p:any){
 if(p.selectedOrder)return <OrderDetail order={p.selectedOrder} back={()=>p.setSelectedOrder(null)} update={(status:string)=>{p.setOrders((os:Order[])=>os.map(o=>o.id===p.selectedOrder.id?{...o,status}:o));p.setSelectedOrder({...p.selectedOrder,status});p.notify(`Order marked ${status}`)}}/>;
 if(p.view==="dashboard")return <><PageHead eyebrow="FULFILLMENT OVERVIEW" title="Good morning, Taylor" subtitle="Here’s what needs attention at the warehouse." action={<button className="primary" onClick={()=>p.setView("orders")}>Open order queue →</button>}/><div className="stats"><Stat n="6" label="Pending orders" tone="orange"/><Stat n="2" label="Currently picking" tone="blue"/><Stat n="3" label="Out for delivery" tone="purple"/><Stat n="4" label="Low-stock alerts" tone="red"/></div><div className="dashboard-grid"><section className="panel wide-panel"><PanelTitle title="Recently submitted" action="View queue" onClick={()=>p.setView("orders")}/><OrderRows orders={p.orders.slice(0,3)} select={p.setSelectedOrder}/></section><section className="panel"><PanelTitle title="Low stock" action="Manage" onClick={()=>p.setView("products")}/>{p.products.filter((x:Product)=>x.onHand-x.reserved<=x.low).map((x:Product)=><div className="stock-row" key={x.id}><div className="product-icon small">{x.icon}</div><div className="grow"><b>{x.name}</b><small>{x.sku}</small></div><strong>{x.onHand-x.reserved}</strong></div>)}</section><section className="panel"><PanelTitle title="Most requested"/><ol className="ranked"><li><b>Compostable Bowl Lids</b><span>84 units</span></li><li><b>Large Paper Bags</b><span>61 units</span></li><li><b>Receipt Paper</b><span>46 units</span></li></ol></section><section className="panel"><PanelTitle title="Recent adjustments" action="Audit log" onClick={()=>p.setView("movements")}/><AuditMini/></section></div></>;
 if(p.view==="orders")return <><PageHead eyebrow="FULFILLMENT" title="Order queue" subtitle="Search, prepare, and deliver warehouse orders." action={<button className="secondary">Print picking list</button>}/><Filters/><OrderList orders={p.orders} select={p.setSelectedOrder}/></>;
 if(p.view==="products")return <Management title="Product management" subtitle="Add products, set low-stock thresholds, and archive items." button="Add product"><div className="responsive-table"><div className="table-head"><span>Product</span><span>Category</span><span>On hand</span><span>Reserved</span><span>Available</span><span></span></div>{p.products.map((x:Product)=><div className="table-row" key={x.id}><span data-label="Product"><b>{x.name}</b><small>{x.sku} · {x.unit}</small></span><span data-label="Category">{x.category}</span><span data-label="On hand">{x.onHand}</span><span data-label="Reserved">{x.reserved}</span><span data-label="Available"><b className={x.onHand-x.reserved<=x.low?"danger-text":""}>{x.onHand-x.reserved}</b></span><span><button className="dots">•••</button></span></div>)}</div></Management>;
 if(p.view==="categories")return <Management title="Categories" subtitle="Keep the manager catalog organized." button="Add category"><SimpleRows rows={["Packaging","Supplies","Pantry"]} details={["3 products","2 products","1 product"]}/></Management>;
 if(p.view==="locations")return <Management title="Locations" subtitle="Manage destinations and their display order." button="Add location"><SimpleRows rows={["Riverside","Downtown","Northside"]} details={["Active · 18 orders","Active · 24 orders","Active · 11 orders"]} reorder/></Management>;
 if(p.view==="receiving")return <InventoryForm receive notify={p.notify}/>;
 if(p.view==="adjustment")return <InventoryForm notify={p.notify}/>;
 if(p.view==="movements")return <Management title="Inventory movement log" subtitle="A permanent record of every stock change."><Filters/><SimpleRows rows={["Received +24 · Receipt Paper","Reserved −6 · Bowl Lids","Adjusted −2 · Large Paper Bags","Delivered −8 · Hot Sauce"]} details={["Taylor M. · Today, 10:14 AM","WH-1048 · Today, 9:42 AM","Taylor M. · Damaged case","WH-1045 · Aug 9, 2:07 PM"]}/></Management>;
 if(p.view==="users")return <Management title="Users & access codes" subtitle="Manage manager, fulfillment, and administrator access." button="Add user"><SimpleRows rows={["Alex R.","Morgan L.","Taylor M.","Casey J."]} details={["Manager · Riverside · Active","Manager · Downtown · Active","Administrator · Active","Fulfillment · Active"]}/><div className="security-note">🔒 PINs are one-way hashed. Existing codes can be reset, never viewed.</div></Management>;
 return <Management title="Warehouse settings" subtitle="Configure ordering and stock alerts."><div className="settings-form"><label>Warehouse display name<input defaultValue="Habaneros Central Warehouse"/></label><label>Default low-stock threshold<input type="number" defaultValue="8"/></label><label className="toggle-row"><span><b>Show product images</b><small>Display stored image paths in the catalog</small></span><input type="checkbox" defaultChecked/></label><button className="primary" onClick={()=>p.notify("Settings saved")}>Save settings</button></div></Management>;
}

function OrderDetail({order,back,manager,update}:{order:Order;back:()=>void;manager?:boolean;update?:(s:string)=>void}){return <><button className="back" onClick={back}>← Back to orders</button><PageHead eyebrow={order.id} title={`${order.location} order`} subtitle={`Submitted by ${order.manager} · ${order.submitted}`} action={<span className={statusClass(order.status)}>{order.status}</span>}/><div className="split"><section className="panel"><h3>Picking & packing details</h3>{productsSeed.slice(0,order.items>5?4:3).map((x,i)=><div className="pick-row" key={x.id}><span className="pick-num">{i+1}</span><div className="grow"><b>{x.name}</b><small>{x.sku} · {x.unit}</small></div><strong>{i+1} requested</strong>{!manager&&<select defaultValue="Fulfilled"><option>Fulfilled</option><option>Substituted</option><option>Shortage</option><option>Cancelled</option></select>}</div>)}<label>Fulfillment notes<textarea placeholder="Substitutions, shortages, or packing notes…"/></label><label>Delivery note<textarea placeholder="Where and to whom the order was delivered…"/></label></section><section className="panel order-side"><h3>Order details</h3><dl><div><dt>Destination</dt><dd>{order.location}</dd></div><div><dt>Manager</dt><dd>{order.manager}</dd></div><div><dt>Items</dt><dd>{order.items}</dd></div><div><dt>Order note</dt><dd>{order.note||"None"}</dd></div></dl>{!manager&&<><label>Update status</label><div className="status-actions">{["Confirmed","Picking","Out for Delivery","Delivered","Cancelled"].map(s=><button key={s} className={s==="Delivered"?"primary":"secondary"} onClick={()=>update?.(s)}>{s}</button>)}</div><button className="print-button">↗ Print picking list</button></>}</section></div></>}
function InventoryForm({receive,notify}:{receive?:boolean;notify:(s:string)=>void}){return <><PageHead eyebrow="INVENTORY" title={receive?"Receive inventory":"Adjust inventory"} subtitle={receive?"Add incoming warehouse stock with a traceable receipt.":"Correct warehouse stock with a required audit reason."}/><section className="panel form-panel"><label>Product<select><option>Select a product</option>{productsSeed.map(x=><option key={x.id}>{x.name} · {x.sku}</option>)}</select></label><div className="form-grid"><label>{receive?"Quantity received":"Quantity change"}<input type="number" placeholder={receive?"0":"e.g. -2 or 5"}/></label><label>{receive?"Reference / invoice":"Reason code"}<select><option>{receive?"Optional reference":"Select a reason"}</option><option>Damaged</option><option>Count correction</option><option>Spoilage</option></select></label></div><label>{receive?"Receiving note":"Adjustment reason (required)"}<textarea placeholder="Add details for the permanent audit log…"/></label><button className="primary" onClick={()=>notify(receive?"Inventory receipt recorded":"Inventory adjustment recorded")}>{receive?"Receive inventory":"Record adjustment"}</button></section></>}
function PageHead({eyebrow,title,subtitle,action}:{eyebrow:string;title:string;subtitle:string;action?:React.ReactNode}){return <div className="page-head"><div><small>{eyebrow}</small><h1>{title}</h1><p>{subtitle}</p></div>{action&&<div>{action}</div>}</div>}
function Stat({n,label,tone}:{n:string;label:string;tone:string}){return <div className={`stat ${tone}`}><b>{n}</b><span>{label}</span></div>}
function PanelTitle({title,action,onClick}:{title:string;action?:string;onClick?:()=>void}){return <div className="panel-title"><h3>{title}</h3>{action&&<button onClick={onClick}>{action} →</button>}</div>}
function OrderList({orders,select}:{orders:Order[];select:(o:Order)=>void}){return <section className="panel order-list"><OrderRows orders={orders} select={select}/></section>}
function OrderRows({orders,select}:{orders:Order[];select:(o:Order)=>void}){return <div className="orders">{orders.map(o=><button className="order-row" key={o.id} onClick={()=>select(o)}><span><b>{o.id}</b><small>{o.location}</small></span><span><b>{o.manager}</b><small>{o.submitted}</small></span><span>{o.items} items</span><span className={statusClass(o.status)}>{o.status}</span><i>→</i></button>)}</div>}
function Filters(){return <div className="filters"><div className="search">⌕ <input placeholder="Search order, location, manager…"/></div><select><option>All statuses</option></select><select><option>All locations</option></select><input type="date" aria-label="Start date"/></div>}
function Management({title,subtitle,button,children}:{title:string;subtitle:string;button?:string;children:React.ReactNode}){return <><PageHead eyebrow="ADMINISTRATION" title={title} subtitle={subtitle} action={button?<button className="primary">+ {button}</button>:undefined}/><section className="panel management">{children}</section></>}
function SimpleRows({rows,details,reorder}:{rows:string[];details:string[];reorder?:boolean}){return <div>{rows.map((r,i)=><div className="simple-row" key={r}>{reorder&&<span className="drag">⠿</span>}<div className="grow"><b>{r}</b><small>{details[i]}</small></div><span className="status status-delivered">Active</span><button className="secondary">Edit</button></div>)}</div>}
function AuditMini(){return <div><div className="audit-row"><span>−2</span><div><b>Large Paper Bags</b><small>Damaged case · Taylor M.</small></div></div><div className="audit-row"><span>+24</span><div><b>Receipt Paper</b><small>Received · Taylor M.</small></div></div></div>}
function Empty({text,action,onClick}:{text:string;action:string;onClick:()=>void}){return <div className="empty"><p>{text}</p><button className="secondary" onClick={onClick}>{action}</button></div>}
function navIcon(v:View){return ({catalog:"▦",cart:"▣",history:"◷",dashboard:"⌂",orders:"▤",products:"□",categories:"≡",locations:"⌖",receiving:"↓",adjustment:"±",movements:"↕",users:"♙",settings:"⚙"} as Record<View,string>)[v]}
